### ISSUE TITLE
Token do CodeClimate no Github

### ISSUE THREAD

**Issue by neilvcarvalho** [mainosistemas/open-nfe#25]
Sugiro passar a configuração para uma variável de ambiente e expirar o token atual.

**Comment by pedropazello** [comment]
Estou para fazer isso faz um tempo, o Travis permite que você cadastre variáveis de ambiente de forma bem tranquila, mas na hora não encontrei uma forma de ler a variável de ambiente. Não dei muita importância porque é um repositório público.
